language: node_js
node_js:
  - "10"
os: linux
dist: xenial
arch: amd64
install:
  - yarn --frozen-lockfile
before_script:
  - npm install -g @tarojs/cli@3.3.0
script:
  - npm run build:rollup
deploy:
  provider: npm
  email: "3433364@qq.com"
  skip_cleanup: true
  api_key: "745405e9-2e76-4e29-8109-cb4c865c545f"
on:
  tags: true
  branch: master
  tag: latest